import polars as pl

CRSP_DSF_SCHEMA = [
    ('cusip', pl.String),
    ('permno', pl.Int32),
    ('permco', pl.Int32),
    ('issuno', pl.Int32),
    ('hexcd', pl.Int16),
    ('hsiccd', pl.Int32),
    ('date', pl.Date),
    ('bidlo', pl.Float64),
    ('askhi', pl.Float64),
    ('prc', pl.Float64),
    ('vol', pl.Float64),
    ('ret', pl.Float64),
    ('bid', pl.Float64),
    ('ask', pl.Float64),
    ('shrout', pl.Float64),
    ('cfacpr', pl.Float64),
    ('cfacshr', pl.Float64),
    ('openprc', pl.Float64),
    ('numtrd', pl.Int32),
    ('retx', pl.Float64),
]

OPTIONM_OPPRCD_SCHEMA = [
    ('secid', pl.Float64),
    ('date', pl.Date),
    ('symbol', pl.String),
    ('symbol_flag', pl.String),
    ('exdate', pl.Date),
    ('last_date', pl.Date),
    ('cp_flag', pl.String),
    ('strike_price', pl.Float64),
    ('best_bid', pl.Float64),
    ('best_offer', pl.Float64),
    ('volume', pl.Float64),
    ('open_interest', pl.Float64),
    ('impl_volatility', pl.Float64),
    ('delta', pl.Float64),
    ('gamma', pl.Float64),
    ('vega', pl.Float64),
    ('theta', pl.Float64),
    ('optionid', pl.Float64),
    ('cfadj', pl.Float64),
    ('am_settlement', pl.Float64),
    ('contract_size', pl.Float64),
    ('ss_flag', pl.String),
    ('forward_price', pl.Float64),
    ('expiry_indicator', pl.String),
    ('root', pl.String),
    ('suffix', pl.String),
]

